### ISSUE TITLE
Install and Configure RabbitMQ with Docker

### ISSUE THREAD

**Issue by estatedocflow** [estatedocflow/estatedocflow.api#13]
**Description**

Set up RabbitMQ using Docker containers to facilitate message queuing and communication within the real estate service booking platform. Docker containers will simplify the deployment and management of RabbitMQ, ensuring consistency across development and production environments.

**Requirements**

1. Docker Installation:

Ensure Docker is installed on the development machine and deployment environment.

2. Docker Compose Configuration:

Create a docker-compose.yml file to define the RabbitMQ service configuration and dependencies.

```
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ default port for AMQP
      - "15672:15672"  # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
```

3. RabbitMQ Management Console Access:
Expose ports for RabbitMQ (5672 for AMQP and 15672 for management console) in the docker-compose.yml file.

4. Environment Variables:
Set environment variables for RabbitMQ default username (admin) and password (password) in the docker-compose.yml file.
