### ISSUE TITLE
Install PostgreSQL with Docker and Integrate with EF Core

### ISSUE THREAD

**Issue by estatedocflow** [estatedocflow/estatedocflow.api#17]
**Description**

Set up a PostgreSQL database using Docker containers and integrate it with Entity Framework Core (EF Core).

**Requirements**

1. Docker Compose Configuration:

```
version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "real_estate_db"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

```

2. Entity Framework Core Integration:

Configure EF Core to connect to the PostgreSQL database using the Npgsql provider.

```
// DbContext class for PostgreSQL
public class RealEstateDbContext : DbContext
{
    public RealEstateDbContext(DbContextOptions<RealEstateDbContext> options) : base(options)
    {
    }

    public DbSet<Booking> Bookings { get; set; }
    public DbSet<Customer> Customers { get; set; }
    // Define other DbSet properties for database entities
}
```

3. Connection String Configuration:

Define the connection string in appsettings.json and appsettingsdev.json to connect to the PostgreSQL database.

```
{
  "ConnectionStrings": {
    "RealEstateDbConnection": "Server=localhost;Port=5432;Database=real_estate_db;User Id=username;Password=password;"
  }
}
```
